# Patroni configuration
patroni_version: "3.0"
patroni_docker_image: "ghcr.io/zalando/spilo-16:3.0-p1"
patroni_scope: "postgres-cluster"
patroni_namespace: "/service/"

# Network configuration
patroni_port: 5432
patroni_restapi_port: 8008
patroni_replication_port: 5433

# PostgreSQL configuration
postgresql_version: "16"
postgresql_data_dir: "/var/lib/postgresql/data"
postgresql_wal_dir: "/var/lib/postgresql/wal"
postgresql_parameters:
  max_connections: "100"
  shared_buffers: "1GB"
  wal_level: "logical"
  hot_standby: "on"

# Cluster configuration
patroni_nodes: []
  # - name: node1
  #   ip: 192.168.1.10
  #   etcd_ip: 192.168.1.100
  # - name: node2  
  #   ip: 192.168.1.11
  #   etcd_ip: 192.168.1.100

# Etcd configuration
etcd_servers: []
  # - "192.168.1.100:2379"

# PgBouncer configuration
pgbouncer_enabled: true
pgbouncer_port: 6432
pgbouncer_pool_mode: "transaction"
pgbouncer_max_client_conn: "1000"
pgbouncer_default_pool_size: "20"

# Backup configuration
backup_enabled: true
backup_method: "pgbackrest"  # pgbackrest, wal-g, or custom
backup_s3_bucket: "my-postgres-backups"
backup_s3_region: "us-east-1"
backup_retention_days: 30
backup_schedule: "0 2 * * *"

# Management
databases: []
  # - name: app_db
  #   owner: app_user
  #   encoding: "UTF8"

users: []
  # - name: app_user
  #   password: "changeme"
  #   databases: ["app_db"]
  #   privileges: ["CONNECT", "CREATE"]

# Docker configuration
docker_network: "patroni-net"
docker_restart_policy: "unless-stopped"