---
- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Create PostgreSQL directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "999"
    group: "999"
    mode: '0755'
  loop:
    - "{{ postgresql_data_dir }}"
    - "{{ postgresql_wal_dir }}"
    - "/etc/patroni"
    - "/var/log/patroni"

- name: Generate Patroni configuration
  template:
    src: patroni.yml.j2
    dest: "/etc/patroni/patroni.yml"
    owner: "999"
    group: "999"
    mode: '0644'

- name: Deploy Patroni container
  community.docker.docker_container:
    name: "patroni-{{ inventory_hostname }}"
    image: "{{ patroni_docker_image }}"
    state: started
    restart_policy: "unless-stopped"
    network_mode: "host"
    volumes:
      - "{{ postgresql_data_dir }}:/home/postgres/pgdata"
      - "{{ postgresql_wal_dir }}:/home/postgres/pgwal"
      - "/etc/patroni/patroni.yml:/etc/patroni/patroni.yml:ro"
    env:
      PATRONI_NAME: "{{ inventory_hostname }}"
      PATRONI_SCOPE: "{{ patroni_scope }}"
    command: "patroni /etc/patroni/patroni.yml"

- name: Wait for Patroni API
  uri:
    url: "http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10

- name: Check Patroni status
  uri:
    url: "http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/patroni"
    method: GET
  register: patroni_status
  failed_when: false

- name: Display Patroni status
  debug:
    msg: "Patroni {{ inventory_hostname }} is {{ patroni_status.json.role }}"

- name: Install backup dependencies
  package:
    name:
      - postgresql-client
      - borgbackup
    state: present
  when: backup_enabled

- name: Configure backup script
  template:
    src: backup.sh.j2
    dest: "/usr/local/bin/postgres-backup.sh"
    mode: '0755'
  when: backup_enabled
  notify: restart patroni