- name: Install etcd dependencies
  package:
    name:
      - wget
      - curl
    state: present

- name: Create etcd user and group
  user:
    name: etcd
    system: true
    home: "{{ etcd_data_dir }}"
    shell: /bin/false

- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: '0755'
  loop:
    - "{{ etcd_data_dir }}"
    - "/etc/etcd"
    - "/var/log/etcd"

- name: Download etcd binary
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd.tar.gz"

- name: Extract etcd binary
  unarchive:
    src: "/tmp/etcd.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Install etcd binaries
  copy:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: true
  loop:
    - etcd
    - etcdctl

- name: Create etcd systemd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'

- name: Configure etcd
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: etcd
    group: etcd
    mode: '0640'

- name: Set etcd directory permissions
  file:
    path: "{{ etcd_data_dir }}"
    owner: etcd
    group: etcd
    mode: '0755'
    state: directory

- name: Start and enable etcd service
  systemd:
    name: etcd
    state: started
    enabled: true
    daemon_reload: true

- name: Wait for etcd cluster health
  command: "etcdctl cluster-health"
  environment:
    ETCDCTL_API: "3"
  register: etcd_health
  until: "'cluster is healthy' in etcd_health.stdout"
  retries: 10
  delay: 5
  ignore_errors: true