---
- name: Stop and disable etcd service
  systemd:
    name: "{{ etcd_service }}"
    state: stopped
    enabled: no

- name: Remove etcd systemd service
  file:
    path: /etc/systemd/system/{{ etcd_service }}
    state: absent

- name: Stop etcd container
  docker_container:
    name: "{{ etcd_cluster }}"
    state: stopped
    force_kill: yes
  ignore_errors: yes

- name: Remove etcd container
  docker_container:
    name: "{{ etcd_cluster }}"
    state: absent
  ignore_errors: yes

- name: Remove etcd Docker image
  docker_image:
    name: "{{ etcd_docker_image }}"
    state: absent
  ignore_errors: yes

- name: Remove etcd data directory
  file:
    path: "{{ etcd_data_dir }}"
    state: absent

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Remove Docker (optional)
  package:
    name: docker.io
    state: absent
  when: remove_docker | default(false)

- name: Confirm cleanup
  debug:
    msg: "etcd has been completely removed from {{ inventory_hostname }}"