---
- name: Stop and disable HAProxy service
  ansible.builtin.systemd:
    name: "{{ haproxy_container_name }}"
    state: stopped
    enabled: false

- name: Remove HAProxy systemd service
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ haproxy_container_name }}.service"
    state: absent

- name: Remove HAProxy container
  ansible.builtin.shell:
    cmd: "docker rm -f {{ haproxy_container_name }} || true"
  args:
    executable: /bin/bash

- name: Remove HAProxy Docker image
  ansible.builtin.shell:
    cmd: "docker rmi {{ haproxy_docker_image }}:{{ haproxy_docker_tag }} || true"
  args:
    executable: /bin/bash
  when: haproxy_remove_image | bool

- name: Clean up HAProxy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ haproxy_config_dir }}"
  when: haproxy_cleanup_dirs | bool

- name: Remove Docker (optional)
  ansible.builtin.include_tasks: uninstall_docker.yml
  when: haproxy_remove_docker | bool

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Display uninstallation summary
  ansible.builtin.debug:
    msg: |
      HAProxy service successfully removed!
      ====================================
      Removed service: {{ haproxy_container_name }}
      Removed container: {{ haproxy_container_name }}
      Removed image: {{ haproxy_remove_image | bool }}
      Cleaned directories: {{ haproxy_cleanup_dirs | bool }}
      Removed Docker: {{ haproxy_remove_docker | bool }}