---
victoriametrics_version: "1.97.1"
victoriametrics_user: "victoriametrics"
victoriametrics_group: "victoriametrics"
timezone: "UTC"

vmstorage_port: 8400  # Inter-node communication
vminsert_port: 8480   # Data ingestion HTTP port
vmselect_port: 8481   # Query HTTP port
vmagent_port: 8429    # Vmagent HTTP port
vmui_port: 8233       # Web UI port

systemd_restart_sec: 10
systemd_limit_nofile: 1000000
systemd_limit_nproc: 50000

cluster_name: "vm-cluster"
replication_factor: "2"
retention_period: "3"

data_dir: "/var/lib/victoriametrics"
cache_dir: "/var/cache/victoriametrics"
snapshots_dir: "/var/lib/victoriametrics-snapshots"