---
- name: Deploy MinIO cluster
  hosts: minio_servers
  become: yes
  
  pre_tasks:
    - name: Ensure data directory exists
      file:
        path: "{{ minio_server_datadirs | first }}"
        state: directory
        owner: "{{ minio_user | default('minio') }}"
        group: "{{ minio_group | default('minio') }}"
        mode: '0755'
  
  roles:
    - role: ansible-minio
      tags: minio
  
  post_tasks:
    - name: Wait for MinIO service to start
      wait_for:
        port: "{{ minio_server_port }}"
        host: "{{ inventory_hostname }}"
        delay: 10
        timeout: 60
      delegate_to: "{{ inventory_hostname }}"