---
- name: restart haproxy container
  community.docker.docker_container:
    name: "{{ haproxy_container_name }}"
    state: restarted
    stop_timeout: 30

- name: reload haproxy configuration
  community.docker.docker_container_exec:
    container: "{{ haproxy_container_name }}"
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg -sf $(pidof haproxy)
    detach: false