---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart haproxy service
  ansible.builtin.systemd:
    name: "{{ haproxy_container_name }}"
    state: restarted

- name: reload haproxy service
  ansible.builtin.systemd:
    name: "{{ haproxy_container_name }}"
    state: reloaded

- name: reload haproxy configuration
  ansible.builtin.shell:
    cmd: "docker exec {{ haproxy_container_name }} haproxy -f /usr/local/etc/haproxy/haproxy.cfg -sf $(pidof haproxy)"
  args:
    executable: /bin/bash